In [1]:
# A minimum spanning tree (MST) is a subset of the edges of a connected, edge-weighted graph that connects all the vertices together without any cycles and with the minimum possible total edge weight.

In [2]:
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import minimum_spanning_tree
import numpy as np

In [3]:
# scipy.sparse.csgraph.minimum_spanning_tree(csgraph, overwrite=False)
# Return a minimum spanning tree of an undirected graph

# A minimum spanning tree is a graph consisting of the subset of edges which together connect all connected nodes, while minimizing the total sum of weights on the edges. This is computed using the Kruskal algorithm.

# Parameters
# :
# csgraph
# array_like or sparse matrix, 2 dimensions
# The N x N matrix representing an undirected graph over N nodes (see notes below).

# overwrite
# bool, optional
# If true, then parts of the input graph will be overwritten for efficiency. Default is False.

# Returns
# :
# span_tree
# csr matrix
# The N x N compressed-sparse representation of the undirected minimum spanning tree over the input (see notes below).

# This routine uses undirected graphs as input and output. That is, if graph[i, j] and graph[j, i] are both zero, then nodes i and j do not have an edge connecting them. If either is nonzero, then the two are connected by the minimum nonzero value of the two.

# This routine loses precision when users input a dense matrix. Small elements < 1E-8 of the dense matrix are rounded to zero. All users should input sparse matrices if possible to avoid it.

# If the graph is not connected, this routine returns the minimum spanning forest, i.e. the union of the minimum spanning trees on each connected component.

# If multiple valid solutions are possible, output may vary with SciPy and Python version.

In [4]:
# Example

# from scipy.sparse import csr_matrix
# from scipy.sparse.csgraph import minimum_spanning_tree
# X = csr_matrix([[0, 8, 0, 3],
#                 [0, 0, 2, 5],
#                 [0, 0, 0, 6],
#                 [0, 0, 0, 0]])
# Tcsr = minimum_spanning_tree(X)
# Tcsr.toarray().astype(int)
# array([[0, 0, 0, 3],
#        [0, 0, 2, 5],
#        [0, 0, 0, 0],
#        [0, 0, 0, 0]])

In [5]:
matrix = csr_matrix([
                    [0,224,234,114,466,436,445,461,104,314,452,28,510],
                    [0,0,217,191,244,214,295,282,147,108,287,237,301],
                    [0,0,0,302,367,378,236,276,146,318,254,228,360],
                    [0,0,0,0,425,379,469,467,155,247,467,134,491],
                    [0,0,0,0,0,72,241,178,377,188,210,478,102],
                    [0,0,0,0,0,0,296,239,358,133,267,450,174],
                    [0,0,0,0,0,0,0,68,341,332,34,445,173],
                    [0,0,0,0,0,0,0,0,357,296,44,464,105],
                    [0,0,0,0,0,0,0,0,0,252,348,108,411],
                    [0,0,0,0,0,0,0,0,0,0,313,330,275],
                    [0,0,0,0,0,0,0,0,0,0,0,454,139],
                    [0,0,0,0,0,0,0,0,0,0,0,0,518],
                    [0,0,0,0,0,0,0,0,0,0,0,0,0]])

In [6]:
Tcsr = minimum_spanning_tree(matrix)

In [7]:
Tcsr.toarray().astype(int).sum()

1137

In [8]:
x = Tcsr.toarray().astype(int)

In [9]:
print(x)

[[  0   0   0 114   0   0   0   0 104   0   0  28   0]
 [  0   0   0   0   0   0   0   0 147 108   0   0   0]
 [  0   0   0   0   0   0   0   0 146   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  72   0   0   0   0   0   0 102]
 [  0   0   0   0   0   0   0   0   0 133   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  34   0   0]
 [  0   0   0   0   0   0   0   0   0   0  44   0 105]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]]
